version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: >
      sh -c "mkdir -p /app/data/chroma &&
             chmod 777 /app/data/chroma &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    working_dir: /app
    volumes:
      - .:/app
      - chroma_data:/app/data/chroma
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/support_bot
      - CHROMA_PERSIST_DIR=/app/data/chroma
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  chroma_data:
  redis_data: 